#!/bin/bash
### BEGIN INIT INFO
# Provides: RadialAssistService
# Required-Start:    $all
# Required-Stop:
# Default-Start:     5
# Default-Stop:      6
# Short-Description: Your service description
### END INIT INFO

cd /home/pi/Documents/RadialAssist

# install dependencies, adjust path
pip3 install -r src/requirements.txt
echo "dependencies installed"
grep -q '/home/pi/.local/bin' <<< "$PATH" && echo "PATH is correct" || PATH="$PATH:/home/pi/.local/bin"

# update
wget -q --spider http://google.com > /dev/null
while [ $? -eq 1 ]
do
    ((c++)) && ((c==10)) && c=0 && break
    echo $c
    sleep 2
    wget -q --spider http://google.com > /dev/null
done

wget -q --spider http://google.com > /dev/null
if [ $? -eq 0 ]; then
    eval "$(ssh-agent -s)"
    git pull -f
    git submodule update --init --recursive
else
    echo "Failed to update."
fi

# create log struct
mkdir -p logs
touch logs/logfile.log

# launch
echo "Launching..."
python3 src/start.py >> logs/logfile.log 2>&1
