#!/bin/bash
### BEGIN INIT INFO
# Provides: RadialAssistService
# Required-Start:    $all
# Required-Stop:
# Default-Start:     5
# Default-Stop:      6
# Short-Description: Your service description
### END INIT INFO

cd /home/pi/Documents/RadialAssist

# update
netstat = $(wget -q --spider http://google.com
echo $netstat
while [ $netstat? -eq 1 ]
do
    netstat = $(wget -q --spider http://google.com)
    ((c++)) && ((c==10)) && c=0 && break
    echo $c
    sleep 2
done

if [ $netstat? -eq 0 ]; then
    eval "$(ssh-agent -s)"
    git pull -f
else
    echo "Failed to update."
fi

# create log struct
mkdir -p logs
touch logs/logfile.log

# launch
echo "Launching..."
python3 src/start.py >> logs/logfile.log 2>&1
